version: "3"
services:
  postgres:
    image: postgres
    container_name: postgres
    environment:
      POSTGRES_DB: social_net
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "postgres"
    ports:
      - "5432:5432"
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres" ]
      interval: 1s
      timeout: 1s
      retries: 10
  migrator:
    build:
      context: ./postgres/
      dockerfile: migrator.Dockerfile
    container_name: migrator
    depends_on:
      postgres:
        condition: service_healthy

  social_net_app:
    build:
      context: .
    environment:
      DATABASE_URL: postgres://postgres:postgres@postgres/social_net
    container_name: social_net
    links:
      - migrator
      - postgres
