START TRANSACTION;

CREATE TYPE social_net.gender AS ENUM (
    'Male',
    'Female'
);-- Might be extended?


CREATE TABLE social_net.users
(
    id              BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    user_id         CHAR(64) NOT NULL,
    first_name      VARCHAR(100) NOT NULL,
    second_name     VARCHAR(100) NOT NULL,
    birthdate       TIMESTAMPTZ,
    gender          social_net.gender,
    city            VARCHAR(100),
    biography       VARCHAR(999),
    password_hash   VARCHAR(999) NOT NULL
);

COMMENT ON TABLE  social_net.users                  IS 'Users';

COMMENT ON COLUMN social_net.users.id               IS 'Primary key ID';
COMMENT ON COLUMN social_net.users.user_id          IS 'User ID for integrations';
COMMENT ON COLUMN social_net.users.first_name       IS 'First name';
COMMENT ON COLUMN social_net.users.second_name      IS 'Second name';
COMMENT ON COLUMN social_net.users.birthdate        IS 'Card expiry date';
COMMENT ON COLUMN social_net.users.gender           IS 'User''s gender';
COMMENT ON COLUMN social_net.users.city             IS 'User''s city';
COMMENT ON COLUMN social_net.users.biography        IS 'Users inetersts';
COMMENT ON COLUMN social_net.users.password_hash    IS 'Secret string for password comparing';

COMMIT;
