version: "3.9"
services:
  postgres:
    image: postgres
    environment:
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "postgres"
    ports:
      - "5432:5432"
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres" ]
      interval: 1s
      timeout: 1s
      retries: 10
  migrator:
    build:
      context: .
      dockerfile: migrator.Dockerfile
    container_name: migrator
    environment: 
      PSQL_CONN_STR: postgres://postgres:postgres@postgres
      SN_USER: postgres
    depends_on:
      postgres:
        condition: service_healthy
