version: "3.9"
services:
  postgres:
    image: postgres
    environment:
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "postgres"
    ports:
      - "5432:5432"
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres" ]
      interval: 1s
      timeout: 1s
      retries: 10
  # pgadmin:
  #   image: dpage/pgadmin4
  #   ports:
  #     - "8443:443"
  #     - "8180:80"
  #   environment:
  #     - PGADMIN_DEFAULT_EMAIL=admin@example.com
  #     - PGADMIN_DEFAULT_PASSWORD=test
  #   depends_on:
  #     - postgres
  #   volumes:
  #     - ./servers.json:/pgadmin4/servers.json
  migrator:
    build:
      context: .
      dockerfile: migrator.Dockerfile
    container_name: migrator
    depends_on:
      postgres:
        condition: service_healthy
