version: "3.9"
services:
  pg-1:
    container_name: postgres_1
    image: docker.io/bitnami/postgresql-repmgr:14.9.0
    ports:
      - "6432:5432"
    volumes:
      - pg_1_data:/bitnami/postgresql
      - ./create_extensions.sql:/docker-entrypoint-initdb.d/create_extensions.sql:ro
    environment:
      - POSTGRESQL_POSTGRES_PASSWORD=adminpgpwd4otushw
      - POSTGRESQL_USERNAME=otushwpguser
      - POSTGRESQL_PASSWORD=pgpwd4otushw
      - POSTGRESQL_DATABASE=social_net
      - REPMGR_PASSWORD=repmgrpassword
      - REPMGR_PRIMARY_HOST=pg-1
      - REPMGR_PRIMARY_PORT=5432
      - REPMGR_PARTNER_NODES=pg-1,pg-2,pg-3:5432
      - REPMGR_NODE_NAME=pg-1
      - REPMGR_NODE_NETWORK_NAME=pg-1
      - REPMGR_PORT_NUMBER=5432
      - REPMGR_CONNECT_TIMEOUT=1
      - REPMGR_RECONNECT_ATTEMPTS=2
      - REPMGR_RECONNECT_INTERVAL=1
      - REPMGR_MASTER_RESPONSE_TIMEOUT=5
    restart: unless-stopped
    networks:
      - postgres-ha
    healthcheck:
      test: ["CMD", "pg_isready", "-q", "-d", "postgres", "-U", "postgres"]
      interval: 10s
      timeout: 5s
      retries: 5

  pg-2:
    container_name: postgres_2
    image: docker.io/bitnami/postgresql-repmgr:14.9.0
    ports:
      - "6433:5432"
    volumes:
      - pg_2_data:/bitnami/postgresql
      - ./create_extensions.sql:/docker-entrypoint-initdb.d/create_extensions.sql:ro
    environment:
      - POSTGRESQL_POSTGRES_PASSWORD=adminpgpwd4otushw
      - POSTGRESQL_USERNAME=otushwpguser
      - POSTGRESQL_PASSWORD=pgpwd4otushw
      - POSTGRESQL_DATABASE=social_net
      - REPMGR_PASSWORD=repmgrpassword
      - REPMGR_PRIMARY_HOST=pg-1
      - REPMGR_PRIMARY_PORT=5432
      - REPMGR_PARTNER_NODES=pg-1,pg-2,pg-3:5432
      - REPMGR_NODE_NAME=pg-2
      - REPMGR_NODE_NETWORK_NAME=pg-2
      - REPMGR_PORT_NUMBER=5432
      - REPMGR_CONNECT_TIMEOUT=1
      - REPMGR_RECONNECT_ATTEMPTS=2
      - REPMGR_RECONNECT_INTERVAL=1
      - REPMGR_MASTER_RESPONSE_TIMEOUT=5
    restart: unless-stopped
    networks:
      - postgres-ha

  pg-3:
    container_name: postgres_3
    image: docker.io/bitnami/postgresql-repmgr:14.9.0
    ports:
      - "6434:5432"
    volumes:
      - pg_3_data:/bitnami/postgresql
      - ./create_extensions.sql:/docker-entrypoint-initdb.d/create_extensions.sql:ro
    environment:
      - POSTGRESQL_POSTGRES_PASSWORD=adminpgpwd4otushw
      - POSTGRESQL_USERNAME=otushwpguser
      - POSTGRESQL_PASSWORD=pgpwd4otushw
      - POSTGRESQL_DATABASE=social_net
      - REPMGR_PASSWORD=repmgrpassword
      - REPMGR_PRIMARY_HOST=pg-1
      - REPMGR_PRIMARY_PORT=5432
      - REPMGR_PARTNER_NODES=pg-1,pg-2,pg-3:5432
      - REPMGR_NODE_NAME=pg-3
      - REPMGR_NODE_NETWORK_NAME=pg-3
      - REPMGR_PORT_NUMBER=5432
      - REPMGR_CONNECT_TIMEOUT=1
      - REPMGR_RECONNECT_ATTEMPTS=2
      - REPMGR_RECONNECT_INTERVAL=1
      - REPMGR_MASTER_RESPONSE_TIMEOUT=5
    restart: unless-stopped
    networks:
      - postgres-ha

  # social_net_app:
  #   build:
  #     context: .
  #   # environment:
  #     # DATABASE_URL: postgres://postgres:postgres@postgres/social_net
  #   container_name: social_net
  #   ports:
  #     - "8083:8083"
  #   links:
  #     - pg-2

  migrator:
    build:
      context: ..
      dockerfile: migrator.Dockerfile
    container_name: migrator
    environment:
      PSQL_CONN_STR: "postgres://postgres:adminpgpwd4otushw@pg-1"
      SN_USER: postgres
    depends_on:
      pg-1:
        condition: service_healthy
    networks:
      - postgres-ha


networks:
  postgres-ha:
    driver: bridge

volumes:
  pg_1_data:
  pg_2_data:
  pg_3_data: